name: quark-bot

services:
  quarkbot:
    image: lzylipu/quarkbot:latest
    container_name: quark-bot-nonebot
    environment:
      PORT: 8080
      SUPERUSER: 1234567890
      TELEGRAM_BOT_TOKEN: bot_token
      METUBE_ENDPOINT: http://10.10.0.2:8081
      SIMPLE_COMMAND: "1"
      PROGRESS_ENABLED: "true"
      PROGRESS_INTERVAL_SECONDS: "5"
      PROGRESS_TIMEOUT_SECONDS: "1800"
    restart: unless-stopped
    network_mode: host
