#!/usr/bin/env bash
set -e

cat > /app/.env.prod <<EOF
HOST=0.0.0.0
PORT=${PORT:-8080}
SUPERUSERS=["${SUPERUSER}"]
COMMAND_START=["/", ""]

DRIVER=~fastapi+~httpx

telegram_bots=[{"token": "${TELEGRAM_BOT_TOKEN}"}]

METUBE_ENDPOINT=${METUBE_ENDPOINT}
SIMPLE_COMMAND="${SIMPLE_COMMAND:-1}"
PROGRESS_ENABLED=${PROGRESS_ENABLED:-true}
PROGRESS_INTERVAL_SECONDS=${PROGRESS_INTERVAL_SECONDS:-5}
PROGRESS_TIMEOUT_SECONDS=${PROGRESS_TIMEOUT_SECONDS:-1800}
EOF

exec python /app/bot.py
