#!/usr/bin/env bash
set -e

cat > /app/.env.prod <<EOF
HOST=0.0.0.0
PORT=${PORT}
SUPERUSERS=["${SUPERUSER}"]
COMMAND_START=["/",""]

DRIVER=~fastapi+~httpx

telegram_bots=[{"token":"${TELEGRAM_BOT_TOKEN}"}]

METUBE_ENDPOINT=${METUBE_ENDPOINT}
SIMPLE_COMMAND="${SIMPLE_COMMAND}"
PROGRESS_ENABLED=${PROGRESS_ENABLED}
PROGRESS_INTERVAL_SECONDS=${PROGRESS_INTERVAL_SECONDS}
PROGRESS_TIMEOUT_SECONDS=${PROGRESS_TIMEOUT_SECONDS}
EOF

exec python /app/bot.py
